### ISSUE TITLE
Catch no responses (object 'Idlist' not found error)

### ISSUE THREAD

**Issue by ChasNelson1990** [felixfan/PubMedWordcloud#3]
Great package, very much enjoying how easy it is to use.

When I run the `getPMIDsByKeyWords` function with options that return 0 results (confirmed on PubMed website) I get the following error:
```
>> getPMIDsByKeyWords(journal = "nature", keys = "cheese", dFrom = 2017)

Error in getPMIDsByKeyWords(journal = "nature", keys = "cheese", dFrom = 2017): object 'Idlist' not found
Traceback:
1. getPMIDsByKeyWords(journal = "nature", keys = "cheese", dFrom = 2017)
```

I think this just needs some sort of catch to return an empty vector in this case?

**Comment by felixfan** [comment]
thanks. fixed.
