### ISSUE TITLE
Error in SSL

### ISSUE THREAD

**Issue by millersan** [felixfan/PubMedWordcloud#6]
Thanks for you great packages!
I tried to used this packages, but it always return error like this, could you help me please?

`pmid1=getPMIDs(author="Yan-Hui Fan",dFrom=2007,dTo=2014,n=10)
pmid1`

`Error in function (type, msg, asError = TRUE)  : 
  error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`

**Comment by sihanwusean** [comment]
I am having the same issue. Not sure how to fix it...

**Comment by felixfan** [comment]
I just tried PubMedWordcloud_0.3.6 and got no error.  if you are using previous version, please reinstall it
`install.packages("PubMedWordcloud", dependencies = TRUE)`
